modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="tritone"
version="${file.jarVersion}"
displayName="Tritone"
updateJSONURL="https://github.com/dayo05/discordMumble"
authors="Dayo"
# The description text for the mod (multi line!) (#mandatory)
description='''
Tritone the distance based volume controller for discord
'''

[[dependencies.tritone]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.tritone]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
